#gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/E11NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/E11NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/E21NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/E21NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/E25NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/E25NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/E43NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/E43NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/E44NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/E44NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/E52NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/E52NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/E53NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/E53NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/EL07NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/EL07NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/EL08NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/EL08NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/EL12NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/EL12NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/EL16NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/EL16NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/EL18NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/EL18NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/EL19NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/EL19NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/EL26NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/EL26NDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_normal/EL29NDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_normal/EL29NDrecaled.bam.allelicCounts.tsv
#gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/E11TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/E11TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/E21TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/E21TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/E25TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/E25TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/E43TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/E43TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/E44TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/E44TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/E52TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/E52TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/E53TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/E53TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/EL07TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/EL07TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/EL08TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/EL08TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/EL12TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/EL12TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/EL16TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/EL16TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/EL18TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/EL18TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/EL19TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/EL19TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/EL26TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/EL26TDrecaled.bam.allelicCounts.tsv
gatk CollectAllelicCounts -L hs37d5.fa.interval_list -I bams_tumor/EL29TDrecaled.bam -R hg19_ref/hs37d5.fa -O bams_tumor/EL29TDrecaled.bam.allelicCounts.tsv
