gatk CollectReadCounts -I bams_tumor/E11TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/E11TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/E21TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/E21TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/E25TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/E25TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/E43TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/E43TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/E44TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/E44TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/E52TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/E52TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/E53TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/E53TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/EL07TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/EL07TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/EL08TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/EL08TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/EL12TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/EL12TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/EL16TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/EL16TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/EL18TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/EL18TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/EL19TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/EL19TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/EL26TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/EL26TDrecaled.bam.counts.hdf5
gatk CollectReadCounts -I bams_tumor/EL29TDrecaled.bam -L hs37d5.fa.interval_list --interval-merging-rule OVERLAPPING_ONLY -O bams_tumor/EL29TDrecaled.bam.counts.hdf5
