#depth
/mnt/X500/farmers/linhx/bin/tools/bam_ultrafast_coverage_cal_wgs.py -b /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/bam/13_normal_bam/E1TD/recaled.bam > /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/oncoAI_score/E1/stat/E1.depth.stat
#gender
/mnt/X500/farmers/linhx/bin/tools/check_sex/sexuality_identify_all.pl /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/bam/13_normal_bam/E1TD/recaled.bam > /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/oncoAI_score/E1/stat/E1.gender.stat
#insert
sh /mnt/X500/farmers/linhx/bin/oca/insert_dis_command.sh /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/bam/13_normal_bam/E1TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/oncoAI_score/E1/E1/stat
#GC
/mnt/X500/farmers/linhx/bin/miniconda3/envs/freec/bin/python /mnt/X500/farmers/linhx/bin/software/freec_code/bamTo1DKsMatAndEigen_density.py --in_cram /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/bam/13_normal_bam/E1TD/recaled.bam --out_prefix /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/oncoAI_score/E1/GC/E1 --region_bed /mnt/X500/farmers/linhx/bin/software/freec_code/hs37d5_24.genome.region.bed --w_len 500000 --min_mapq 60 --residual 1e-10 --mappability  /mnt/X500/farmers/linhx/bin/software/freec_code/wgEncodeCrgMapabilityAlign100mer.hs37d5_24.bw --min_mappability 0.75  --gene_density /mnt/X500/farmers/linhx/bin/software/freec_code/Homo_sapiens.GRCh37.85.gtf.gene --scale True  --gcbase  /mnt/X500/farmers/linhx/bin/software/freec_code/hg19.gc5Base.hs37d5_24.bw
#ichorCNA(tumor fraction)
/mnt/X500/farmers/linhx/bin/cna/run_ichorCNA_with_pon.py /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/bam/13_normal_bam/E1TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/oncoAI_score/E1 E1

#zscore(arm_zscore)
export R_LIBS=/usr/local/lib64/R/library:/usr/local/opt/lib64/R/library:$R_LIBS
mkdir /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/arm_zscore/E1TD 
python /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/arm_zscore/zscore_main.py -b /mnt/Archive001/farmers/zhuxl/ESC_Cheng_WGS/13_normal_bam/E1TD/sorted_E1TD_BDHG192031535-1a_BHWTFCDSXX-new_L3.bam -o /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/arm_zscore/E1TD -s E1TD

#bam_to_fraggc(ai_zscore)
mkdir -p /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/ocf/
/mnt/X500/farmers/linhx/bin/miniconda3/envs/py27/bin/samtools index /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/breakdancer/E1.fixmate.sort.bam
/mnt/X500/farmers/linhx/bin/tools/bam_to_fggc/bam_to_fraggc/bam_to_fraggc_v1.4 --bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/breakdancer/E1.fixmate.sort.bam --reference /mnt/X500/farmers/linhx/bin/ref/hs37d5.fa --maxFragSize 1000000 --minFragSize 100 --removeDuplicate --mapQual 30 | gzip -c -1 > /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/E1.fggc.tsv.gz && /mnt/X500/farmers/linhx/bin/miniconda3/envs/oncoAi/bin/Rscript /mnt/X500/farmers/linhx/bin/oca/fggc_to_feature_fast_v1.0.1.r /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/E1.fggc.tsv.gz /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/cfg /mnt/X500/farmers/linhx/bin/oca/data_prepare/AB.rds /mnt/X500/farmers/linhx/bin/oca/data_prepare/wgEncodeDukeMapabilityRegionsExcludable_hg19.auto.bed
/mnt/X500/farmers/linhx/bin/miniconda3/bin/tabix /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/E1.fggc.tsv.gz -T /mnt/X500/farmers/linhx/bin/ref/region_bed/combine.black.merge.complement.bed |cut -f 1,2,3,6 |  gzip -1 -c > /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/E1.fggc.tsv.remove_black.gz
zcat /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/E1.fggc.tsv.gz | cut -f 1,2,3 > /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/E1.fggc.tsv
bedtools intersect -b /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/E1.fggc.tsv -a /mnt/X500/farmers/lijun/prj/delfi/linqing/WGS_DHS/software/pipelineOCFprofiler/lib/pick.all.OC.bed/all.OC.bed -wo -sorted > /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/ocf/ocr.inter.bed
perl /mnt/X500/farmers/linhx/bin/oca/ocf_lib/sync.pl /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/ocf/ocr.inter.bed /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/ocf > /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/ocf/sync.lst
perl /mnt/X500/farmers/linhx/bin/oca/ocf_lib/quant.pl /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/ocf/sync.lst > /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/ocf/ocf.value
/mnt/X500/farmers/linhx/bin/miniconda3/envs/oncoAi/bin/Rscript /mnt/X500/farmers/linhx/bin/oca/machine_learning/04.xgboost2_predict_onesample.r /mnt/X500/farmers/linhx/ctDNA/wgs_all/batch_combine_20200316_oncoAi_preRelease/cancer_5m.rds /mnt/X500/farmers/linhx/ctDNA/wgs_all/batch_combine_20200316_oncoAi_preRelease/health_5m.rds /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/E1.bins_5Mbcompartments.rds /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/result/wgs_model/bam2fraggc/E1/
