ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E1TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E1TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E1ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E1NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E10TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E10TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E10ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E10NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E15TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E15TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E15ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E15NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E18TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E18TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E18ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E18NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E2TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E2TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E2ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E2NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E23TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E23TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E23ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E23NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E24TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E24TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E24ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E24NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E26TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E26TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E26ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E26NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E31TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E31TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E31ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E31NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E33TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E33TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E33ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E33NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E35TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E35TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E35ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E35NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E47TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E47TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E47ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E47NDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E51TD/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_tumor/E51TDrecaled.bam
ln -s /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_bam/E51ND/recaled.bam /mnt/X500/farmers/zhuxl/Project/ESC_Cheng_WGS/13_normal_analysis/CNV/gatk/bams_normal/E51NDrecaled.bam
